package com.example.hatching.Controller;

import com.example.hatching.Model.Eggs;
import com.example.hatching.Repository.HatchingRepository;
import com.example.hatching.Service.HatchingService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController()
public class HatchingController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private HatchingRepository hatchingRepository;
    @Autowired
    private HatchingService hatchingService;
    @PostMapping("/egg")
    public @ResponseBody Eggs addEggs(
            @RequestParam String name,
            @RequestParam Integer hatchingTime) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        final Eggs egg = new Eggs();
        egg.setName(name);
        egg.setHatchingTime(hatchingTime);
        return hatchingService.save(egg);
    }
    @GetMapping("/egg")
    public @ResponseBody Iterable<Eggs> getAllUsers() {
        // This returns a JSON or XML with the users
        return hatchingService.getAllUsers();
    }
}

    //@PostMapping("/eggs/")

