
### add eggs
POST http://localhost:8081/addEgg?name=bulbizarre&hatchingTime=1&no=001

### delete egg
DELETE http://localhost:8081/deleteEgg?id=9

### add pokemon
POST http://localhost:8081/addPokemon?name=Tartard&level=99&no=062

### delete pokemon
DELETE http://localhost:8081/deletePokemon?id=2

### get all pokemons
GET http://localhost:8081/pokemons

### get all eggs
GET http://localhost:8081/eggs
