### Get post to see all egg to buy

GET http://localhost:8084/getAllEggToBuy

### Delete request for remove one egg
DELETE http://localhost:8084/removeEgg?id=30

### Get post to have price of one egg

GET http://localhost:8084/getPriceEgg?id=6

### Delete request for remove all eggs in store

DELETE http://localhost:8084/deleteAllEgg