### Send POST request with json body
POST http://localhost:8084/add
Content-Type: application/json

{
  "name": "Dracofeu",
  "level": 2,
  "price": 123,
  "hatchingTime" : 12
}

### Post request to have list of 4 random eggs

POST http://localhost:8084/list_egg?size=4
