### add dresseur
POST http://localhost:8080/addDresseur?name=Samom&xp=120&level=5&gold=200

### get all dresseurs
GET http://localhost:8080/dresseurs

### delete dresseur
DELETE http://localhost:8080/deleteDresseur?id=1

### add gold
PUT http://localhost:8080/addGold?id=1&amount=1000

### remove gold
PUT http://localhost:8080/removeGold?id=1&amount=696

### add xp
PUT http://localhost:8080/addXp?id=1&amount=15

### get dresseur by id
GET http://localhost:8080/dresseur?id=1
